server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: http://xx.xx.xx.xx:9090/xxx/xx-spring-config.git
          password: xxxx   # --spring.cloud.config.server.git.password=xxx
          search-paths: config
          default-label: master
          clone-on-start: true

